// Generated by Website Factory. Update via the factory pipeline, not by hand.

export interface MenuItem {
  name: string;
  native?: string;
  nr?: string;
  description?: string;
  price: string;
  spicy?: boolean;
  vegan?: boolean;
  note?: string;
}

export type MenuCategory = {
  id: string;
  label: string;
  native?: string;
  intro?: string;
  items: MenuItem[];
};

export const menuDataGeneratedFromFactory = true;

export const menuImageUrls: string[] = [
  "https://lh3.googleusercontent.com/gps-cs-s/APNQkAGcbLgXGN93_aemQWyWEjPupauOYxHuOI5P4trJRmlMJFQELzbeirUgUJKTtiBbcARIyx1UsXcFNjSLjjh2NXArFuc1ubRIMcBHY6uVPSaT6naCp-SZF672fV8Sz6QNB68ddmVtt89gzOiW=w1600-h1200",
  "https://lh3.googleusercontent.com/gps-cs-s/APNQkAE-DQQRofzRU_1vFXKmz9j4JNa-4XF2QCp6PPXaIb1h8rZRdVT3Q2YmsIZFlvs-h59bYQ15NeoXRENYwfEXOY3AIye_8rWp5bifUMUFQG56tkPj4-Kd9ZJf7vs55XrC8I3Pwh-WPexPZHZm=w1600-h1200",
  "https://lh3.googleusercontent.com/gps-cs-s/APNQkAEGyV_tLK3ZLT6EavEw2y5sraC9TtQPPIuw_z5f1r14rF0CgFqIBjiEgQvFIUKrHmBuIDX6ihgW4snVRRZyLpzLUEvnNhrUYgl300LGCG1dAC_zBixKtO50Tg6HF08Ne-GdtLVz1f7jeidn=w1600-h1200",
  "https://lh3.googleusercontent.com/gps-cs-s/APNQkAHA3LVTPDtz4XLQxoP3RjddH_zXP4gd74V1XoomcesYFmyRI2IZ5pktYkkq7JtEcbLJ1kBiVfJhNiXz9XW6gYhf-npdNGp_Nb7aH94LS3KlH6GbdmVqaEB5TrPE5HSIabtFPz7Vs7IKSmR5=w1600-h1200",
  "https://lh3.googleusercontent.com/gps-cs-s/APNQkAHR3sGSbzseWGsBMQflHi87U4gmVZdPGG6y2kXhpTPWnUUmce_8utMZo-0lM2eFxtCTZsH4o5TY1CDn5Z9viwFFQZcIzS2BaUs07dNwo5HthERtukFzWJPtzX-7GaFqGSHT_ruXD3edAh8=w1600-h1200",
  "https://lh3.googleusercontent.com/gps-cs-s/APNQkAHfKTgR70e5cy73lvtSk2m2onE6Ar3ByzkFqC-eJiDnVlnftsADaOKfCan7m8Jc_nqN0AlB671tYuE9I5ht_-H_2GCR4l4mBn1tGo5mEQP5SDsGRW8XjO1OdS5GHyjUuBhaKOH6VOyU20B4=w1600-h1200",
  "https://lh3.googleusercontent.com/gps-cs-s/APNQkAFIwogHZokx0fY-5cA58zeauXEoyVHJigidFWJmPGeSng9NNxlvl9VEFBzs4dSrvG6hfCitcvXMIn_P9RMznCzxa-o2b9_Myjaaa8AnJCgZgG_o3e3Rq_JpRRy6Ijh8S-VMYvO8Petgwe-2=w1600-h1200",
  "https://lh3.googleusercontent.com/gps-cs-s/APNQkAHmdP3ZnZwucriNn1bxVUyob7nAmHllsuhD6EqnkLlinKlOK1Z2jJjh2CaUyn_M5sR4rYzpE_myLlIDX-7-zSg0BwjYmwGMgRJalrcUAzTsWjQ8qXRDo6rdCxvRXOIMGMlVlrr_2sfbbmVW=w1600-h1200",
  "https://lh3.googleusercontent.com/gps-cs-s/APNQkAEN0y-3xXShE3MAemnlq9RYngK5vwPe1Razwkmnyp9p-psswfJDcIULSoDHustkpotfRlys8LNgsOAb9_G9LkpExTIti09RC3Ktbl5CMw5RJmtjFoFBuqhTufRdvnJf7CA7hvqQhbzB2NLG=w1600-h1200",
  "https://lh3.googleusercontent.com/gps-cs-s/APNQkAHfij7P9BE1Q0GNaAke8xDDX14GigGD0_CzHXCSTUx5yi2kgXuP7izBuMPJCHS1ED82ZLWNkGEAwhIv49SywHY4mNXkWzzH2eKOddPwHdjxeqPDxeSOM5F7YzGghRiTp20UKtqM8YQODxAt=w1600-h1200",
  "https://lh3.googleusercontent.com/gps-cs-s/APNQkAEvyl4BEaaVVGP52opAo8hlsZpg8sDr9xS71YNF17EUEst6h_8s60J1LCXOR9Nx_6cj5R4ZHC8vgdCZ_zrUiadZ75NY4uQ9iJ5M5Xn-tBLJ8WVPkTZGnLymYIHGxZjz6x6pYkvFrSbMK7kA=w1600-h1200",
  "https://lh3.googleusercontent.com/gps-cs-s/APNQkAGcH8YCAbL1DiT_eEAEUVcQlbIiRYdz156H6i1MyfuMehxYhaH9yA4i9l5Q-gQvoKuU3eVkQ9TrfgOTn8xkvMj5kB-ZbYq63Z7yaQiFxZTAMzXXS1KG0SbfqPgnXHj-4hWFhWg6hNDfPhzD=w1600-h1200"
];

export const menuCategories: MenuCategory[] = [
  {
    "id": "drehspieb-spezialitaten",
    "label": "Drehspieb Spezialitäten",
    "items": [
      {
        "name": "Drehspieß im Brot",
        "description": "Mit hähnchenfleisch, salat, soße",
        "price": "6,50"
      },
      {
        "name": "Drehspieß Yufka",
        "description": "Mit hähnchenfleisch, salat, soße",
        "price": "7,00"
      },
      {
        "name": "Drehspießteller",
        "description": "Mit hähnchenfleisch, pommes, salat, soße",
        "price": "10,00"
      },
      {
        "name": "Drehspieß im Brot",
        "description": "Mit hackfleisch vom kalb, salat, soße",
        "price": "7,00"
      },
      {
        "name": "Drehspieß mit Yufka",
        "description": "Mit hackfleisch vom kalb, salat, soße",
        "price": "7,50"
      },
      {
        "name": "Drehspieß-Teller",
        "description": "Mit hackfleisch vom kalb, pommes, salat, soße",
        "price": "11,00"
      },
      {
        "name": "Drehspieß Box",
        "description": "Mit hähnchenfleisch, salat, soße",
        "price": "6,50"
      },
      {
        "name": "Drehspieß Box",
        "description": "Mit hackfleisch, salat, soße",
        "price": "7,00"
      },
      {
        "name": "Lahmacun",
        "description": "Mit hackfleisch, mit salat und soße",
        "price": "6,50"
      },
      {
        "name": "Schüler Drehspieß",
        "description": "Mit hähnchenfleisch, salat, soße",
        "price": "5,00"
      },
      {
        "name": "Schüler Drehspieß",
        "description": "Mit hackfleisch, salat, soße",
        "price": "5,50"
      }
    ]
  },
  {
    "id": "sandwich-spezialitaten",
    "label": "Sandwich Spezialitäten",
    "items": [
      {
        "name": "Hähnchen Sandwich",
        "description": "Mit hähnchenkeule, salat, soße",
        "price": "7,00"
      },
      {
        "name": "Köfte Sandwich",
        "description": "Mit türkische frikadellen, salat, soße",
        "price": "7,50"
      },
      {
        "name": "Hackfleisch Sandwich",
        "description": "Mit hackfleisch vom kalb, salat, soße",
        "price": "7,50"
      },
      {
        "name": "Gemüse Sandwich",
        "description": "Mit gegrilltes gemüse, salat, soße",
        "price": "6,50"
      },
      {
        "name": "Wurst Sandwich",
        "description": "Mit feuerwurst, salat, soße",
        "price": "7,50"
      },
      {
        "name": "Lammspieß Dürüm",
        "description": "Mit lammspieß, salat, soße",
        "price": "8,50"
      }
    ]
  },
  {
    "id": "mini",
    "label": "Mini",
    "items": [
      {
        "name": "Mini-Pizza",
        "price": ""
      }
    ]
  },
  {
    "id": "grillspezialitaten",
    "label": "Grillspezialitäten",
    "items": [
      {
        "name": "Sandwich Hähnchen",
        "price": "7,00"
      },
      {
        "name": "Sandwich Köfte",
        "price": "7,50"
      },
      {
        "name": "Sandwich Kalbfleisch",
        "price": "7,50"
      },
      {
        "name": "Sandwich Gemüse",
        "price": "6,50"
      },
      {
        "name": "Sandwich Feuerwurst",
        "price": "7,50"
      },
      {
        "name": "Sandwich Lammspieß",
        "price": "8,50"
      }
    ]
  },
  {
    "id": "pizza-30cm-durchmesser",
    "label": "Pizza 30cm Ø Durchmesser",
    "items": [
      {
        "name": "Pizza Magherita",
        "price": "7,00"
      },
      {
        "name": "Pizza Thunfisch",
        "price": "10,50"
      },
      {
        "name": "Pizza Sucuk",
        "price": "10,00"
      },
      {
        "name": "Pizza Vegetarisch",
        "price": "10,00"
      },
      {
        "name": "Pizza Drehspieß",
        "price": "12,00"
      },
      {
        "name": "Pizza Grillhausspezial",
        "price": "11,00"
      },
      {
        "name": "Mini Pizza 20ø",
        "price": "5,00"
      }
    ]
  },
  {
    "id": "beilagen",
    "label": "Beilagen",
    "items": [
      {
        "name": "Pommes Klein",
        "price": "2,50"
      },
      {
        "name": "Pommes Groß",
        "price": "3,50"
      },
      {
        "name": "Salat Klein",
        "price": "3,50"
      },
      {
        "name": "Salat Groß",
        "price": "5,00"
      },
      {
        "name": "Hamburger",
        "price": "6,50"
      },
      {
        "name": "Cheesburger",
        "price": "7,50"
      },
      {
        "name": "Nuggets + Pommes",
        "price": "8,50"
      },
      {
        "name": "Falafel 6 Stück",
        "price": "7,00"
      }
    ]
  },
  {
    "id": "schuler-kebab",
    "label": "Schüler Kebab",
    "items": [
      {
        "name": "Drehspieß Für Schüler Hähnchen",
        "price": "5,00"
      },
      {
        "name": "Drehspieß Für Schüler Kalb",
        "price": "5,50"
      }
    ]
  },
  {
    "id": "mini-pizza-softdrink-0-33-l",
    "label": "Mini-Pizza + Softdrink (0,33 L)",
    "items": [
      {
        "name": "Mini-Pizza",
        "description": "Wählbar aus allen mini-pizza-varianten",
        "price": ""
      },
      {
        "name": "Softdrink (0,33 L)",
        "price": ""
      }
    ]
  },
  {
    "id": "drehspie-im-brot-softdrink",
    "label": "Drehspieß im Brot + Softdrink",
    "items": [
      {
        "name": "Drehspieß im Brot",
        "price": ""
      },
      {
        "name": "Softdrink",
        "price": ""
      }
    ]
  },
  {
    "id": "zusatzliche-optionen",
    "label": "Zusätzliche Optionen",
    "items": [
      {
        "name": "Extra Käse",
        "price": "1,00"
      },
      {
        "name": "Große Portion",
        "description": "(Mehr fleisch oder gemüse)",
        "price": "2,00"
      },
      {
        "name": "Beilage",
        "description": "(Pommes oder salat)",
        "price": "2,50"
      },
      {
        "name": "Extra Soße",
        "price": "0,50"
      },
      {
        "name": "Extra Sucuk",
        "price": "1,50"
      }
    ]
  },
  {
    "id": "zusatzliche-zutaten-fur-pizza-mini-pizzen",
    "label": "Zusätzliche Zutaten Für Pizza & Mini-Pizzen",
    "items": [
      {
        "name": "Käse",
        "description": "Mozzarella, parmesan, gouda",
        "price": "1,00"
      },
      {
        "name": "Gemüse",
        "description": "Champignons, paprika, zwiebeln, oliven",
        "price": "0,50"
      },
      {
        "name": "Fleisch",
        "description": "Hähnchenfleisch, kalbfleisch, sucuk, thunfisch",
        "price": "1,50"
      }
    ]
  },
  {
    "id": "getranke",
    "label": "Getränke",
    "items": [
      {
        "name": "Coca-Cola",
        "price": "2,00"
      },
      {
        "name": "Coca-Cola Zero",
        "price": "2,00"
      },
      {
        "name": "Fanta",
        "price": "2,00"
      },
      {
        "name": "Sprite",
        "price": "2,00"
      },
      {
        "name": "Mezzo Mix",
        "price": "2,00"
      },
      {
        "name": "Mineralwasser",
        "description": "(Still oder sprudelnd)",
        "price": ""
      },
      {
        "name": "Ayran",
        "price": ""
      },
      {
        "name": "Spezi",
        "price": ""
      }
    ]
  },
  {
    "id": "vegetarische-spezialitaten",
    "label": "Vegetarische Spezialitäten",
    "items": [
      {
        "name": "Gegrilltes Gemüse im Brot",
        "description": "Mit gegrillte paprika, zucchini, aubergine, salat, soße",
        "price": "6,50"
      },
      {
        "name": "Gemüseteller",
        "description": "Mit gegrilltes gemüse, salat, soße, pommes",
        "price": "9,00"
      },
      {
        "name": "Falafel im Brot",
        "description": "Mit falafel, gegrilltes gemüse, salat, soße",
        "price": "6,00"
      },
      {
        "name": "Lahmacun",
        "description": "Mit salat und soße (ohne fleisch)",
        "price": "5,50"
      }
    ]
  },
  {
    "id": "sonstiges",
    "label": "Sonstiges",
    "items": [
      {
        "name": "Pizza Margherita",
        "price": ""
      },
      {
        "name": "Pizza Thunfisch",
        "description": "Thunfisch, zwiebeln",
        "price": ""
      },
      {
        "name": "Pizza Sucuk",
        "price": ""
      },
      {
        "name": "Pizza Vegetarisch",
        "price": ""
      },
      {
        "name": "Pizza Drehspieß",
        "price": ""
      },
      {
        "name": "Gemüseteller",
        "price": ""
      },
      {
        "name": "Falafel im Brot",
        "price": ""
      },
      {
        "name": "Wasser",
        "description": "Still oder",
        "price": ""
      }
    ]
  }
];
