// Generated by Website Factory. Update via the factory pipeline, not by hand.

export type Review = {
  author: string;
  rating: number;
  text: string;
  time: string;
};

export type ReviewsData = {
  overallRating: number;
  totalRatings: number;
  reviews: Review[];
};

export const reviewsDataGeneratedFromFactory = true;

export const reviewsData: ReviewsData = {
  "overallRating": 4.3,
  "totalRatings": 21,
  "reviews": [
    {
      "author": "UK82",
      "rating": 5,
      "text": "Ein Döner den man regelmäßig Essen möchte. Hier passen alle Zutaten wunderbar zusammen, vom Fleisch, Brot, Salat und Soße. In der Umgebung ist für  mich der Döner geschmacklich der beste und am leckersten, das selbstgemachte Brot ist absolut weiter zu empfehlen !!!! Mein Tip,  um mehr  Aufmerksamkeit zu erhalten wäre die äußerliche Beleuchtung anzupassen es wirkt von außen dunkel wenn man reinschaut.",
      "time": "vor 4 Monaten"
    },
    {
      "author": "traubensaft 145",
      "rating": 5,
      "text": "Also ich war nun schon einige male dort und ich muss sagen dass, ich mit dem Laden Absolut zufrieden bin!\n\nIch habe bisher folgende Gerichte gegessen:\nDöner normal mit viel Zwiebel\nPizza Salami\nKöfte\nYufka\n\nAlle Gerichte die ich dort gegessen habe sind absolut einwandfrei, lecker und der Service ist gut! Meine Empfehlung ist der Yufka, laut das Typen der hinter der Theke steht ist das Yufka-Brot selber gemacht und das schmeckt man! Meiner Meinung nach.",
      "time": "vor 6 Monaten"
    },
    {
      "author": "214sinan",
      "rating": 5,
      "text": "Der Dönerteller war absolut lecker, das Fleisch ist  gut gewürzt und saftig ABSOLUTER GAUMENSCHMAUS. Ich kann es an alle empfehlen kommt vorbei und genießt es. Jetzt haben wir in Eppelheim wieder ein GEILES Döner. Die Preise sind einfach unschlagbar ein Riesen plus Punkt",
      "time": "vor 11 Monaten"
    },
    {
      "author": "lisa.dct_",
      "rating": 5,
      "text": "Bester Vegetarischer Döner den ich je gegessen habe!! Der Inhalt den Döners ist top frisches gegrilltes Gemüse hab ich so noch nie gegessen. Toll!",
      "time": "vor 5 Monaten"
    }
  ]
};
